#!/bin/bash
clear
echo -e "\e[34m Installing core files.....\e[0m"
arc=$(dpkg --print-architecture)
cd $PREFIX/bin
if [[ $arc = "aarch64" ]] || [[ $arc = "arm" ]]
then
rm -rf chr
rm -rf rchr
else
sudo rm -rf chr
sudo rm -rf rchr
fi
cd $HOME
rm -rf r.sh
rm -rf Wordlist
mkdir Wordlist 
cd Wordlist
mkdir tempbin >/dev/null 2>&1
cd tempbin
wget https://raw.githubusercontent.com/avistnm/test/master/chr >/dev/null 2>&1
wget https://raw.githubusercontent.com/avistnm/test/master/rchr >/dev/null 2>&1
chmod 777 *
if [[ $arc = "aarch64" ]] || [[ $arc = "arm" ]]
then
mv * $PREFIX/bin
else
sudo mv * $PREFIX/bin
fi
wget https://raw.githubusercontent.com/avistnm/test/master/r.sh >/dev/null 2>&1
chmod 777 r.sh >/dev/null 2>&1
mv r.sh $HOME >/dev/null 2>&1
cd $HOME
cd Wordlist
rm -rf tempbin >/dev/null 2>&1
rm -rf *

cd $HOME
rm -rf setup
echo -e "\e[34m Installation Successful!!\e[0m"
echo -e "\e[34m Run Script by executing \e[1;32m bash r.sh\e[0m"
